import { IEmail, IMailbox } from '../interfaces/mailAPI.interface';

// Mock Mailboxes
export const MOCK_MAILBOXES: IMailbox[] = [
  { id: 'inbox', name: 'Inbox' },
  { id: 'sent', name: 'Sent' },
  { id: 'drafts', name: 'Drafts' },
  { id: 'trash', name: 'Trash' },
  { id: 'spam', name: 'Spam' },
];

// Mock Emails - 50+ emails để test scroll
export const MOCK_EMAILS: IEmail[] = [
  {
    id: '1',
    mailboxId: 'inbox',
    sender: 'john.doe@example.com',
    subject: 'Project Update - Q4 2024',
    preview: 'Hi team, here is the latest update on our Q4 project deliverables...',
    timestamp: '2024-12-02T10:30:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: true,
  },
  {
    id: '2',
    mailboxId: 'inbox',
    sender: 'sarah.wilson@company.com',
    subject: 'Meeting Notes - Sprint Planning',
    preview: 'Please find attached the meeting notes from today\'s sprint planning session...',
    timestamp: '2024-12-02T09:15:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '3',
    mailboxId: 'inbox',
    sender: 'notifications@github.com',
    subject: '[GitHub] New pull request in main repository',
    preview: 'A new pull request has been opened by @developer123...',
    timestamp: '2024-12-02T08:45:00Z',
    isRead: false,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '4',
    mailboxId: 'inbox',
    sender: 'marketing@newsletter.com',
    subject: 'Weekly Newsletter - Tech Trends',
    preview: 'Top 10 technology trends you should know about this week...',
    timestamp: '2024-12-01T18:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '5',
    mailboxId: 'inbox',
    sender: 'hr@company.com',
    subject: 'Annual Leave Request Approved',
    preview: 'Your annual leave request for December 20-30 has been approved...',
    timestamp: '2024-12-01T16:30:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '6',
    mailboxId: 'inbox',
    sender: 'support@aws.amazon.com',
    subject: 'AWS Billing Statement - November 2024',
    preview: 'Your AWS billing statement for November 2024 is now available...',
    timestamp: '2024-12-01T14:20:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '7',
    mailboxId: 'inbox',
    sender: 'team-lead@company.com',
    subject: 'Code Review Required - Feature Branch',
    preview: 'Please review the new authentication feature implementation...',
    timestamp: '2024-12-01T11:00:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '8',
    mailboxId: 'inbox',
    sender: 'security@company.com',
    subject: 'Security Alert - Unusual Login Activity',
    preview: 'We detected a login from an unusual location. If this was not you...',
    timestamp: '2024-12-01T09:30:00Z',
    isRead: false,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '9',
    mailboxId: 'inbox',
    sender: 'client@business.com',
    subject: 'Re: Proposal Discussion',
    preview: 'Thank you for the detailed proposal. We have a few questions...',
    timestamp: '2024-11-30T17:45:00Z',
    isRead: true,
    isStarred: true,
    hasAttachment: true,
  },
  {
    id: '10',
    mailboxId: 'inbox',
    sender: 'noreply@linkedin.com',
    subject: 'You have 5 new connection requests',
    preview: 'John Smith, Sarah Johnson, and 3 others want to connect with you...',
    timestamp: '2024-11-30T15:20:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '11',
    mailboxId: 'inbox',
    sender: 'dev-team@company.com',
    subject: 'CI/CD Pipeline Update',
    preview: 'The CI/CD pipeline has been updated with new deployment scripts...',
    timestamp: '2024-11-30T13:10:00Z',
    isRead: false,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '12',
    mailboxId: 'inbox',
    sender: 'finance@company.com',
    subject: 'Expense Report Approved',
    preview: 'Your expense report for November has been approved and processed...',
    timestamp: '2024-11-30T10:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '13',
    mailboxId: 'inbox',
    sender: 'admin@jira.com',
    subject: 'Task Assignment - PROJ-1234',
    preview: 'You have been assigned to task PROJ-1234: Implement user dashboard...',
    timestamp: '2024-11-29T16:30:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '14',
    mailboxId: 'inbox',
    sender: 'training@company.com',
    subject: 'Upcoming Training Session - React Advanced',
    preview: 'Register now for the advanced React training session on Dec 15...',
    timestamp: '2024-11-29T14:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '15',
    mailboxId: 'inbox',
    sender: 'notifications@slack.com',
    subject: 'Daily Digest - 12 new mentions',
    preview: 'You were mentioned in #general, #dev-team, and 2 other channels...',
    timestamp: '2024-11-29T12:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '16',
    mailboxId: 'inbox',
    sender: 'product@company.com',
    subject: 'Product Roadmap Q1 2025',
    preview: 'Please review the proposed product roadmap for Q1 2025...',
    timestamp: '2024-11-29T09:30:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: true,
  },
  {
    id: '17',
    mailboxId: 'inbox',
    sender: 'recruiter@company.com',
    subject: 'Interview Scheduled - Senior Developer Position',
    preview: 'Your interview has been scheduled for December 10 at 2:00 PM...',
    timestamp: '2024-11-28T17:00:00Z',
    isRead: false,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '18',
    mailboxId: 'inbox',
    sender: 'webmaster@website.com',
    subject: 'Website Downtime Alert',
    preview: 'We detected downtime on your website at 3:45 AM...',
    timestamp: '2024-11-28T15:30:00Z',
    isRead: true,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '19',
    mailboxId: 'inbox',
    sender: 'design@company.com',
    subject: 'UI/UX Feedback Request',
    preview: 'Could you please provide feedback on the new dashboard designs...',
    timestamp: '2024-11-28T13:20:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '20',
    mailboxId: 'inbox',
    sender: 'api@stripe.com',
    subject: 'Payment Successful - Invoice #12345',
    preview: 'Your payment of $99.00 has been processed successfully...',
    timestamp: '2024-11-28T11:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '21',
    mailboxId: 'inbox',
    sender: 'alerts@monitoring.com',
    subject: 'Server CPU Usage Alert - 85%',
    preview: 'Warning: Server CPU usage has reached 85% on production-1...',
    timestamp: '2024-11-27T18:45:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '22',
    mailboxId: 'inbox',
    sender: 'newsletter@techcrunch.com',
    subject: 'TechCrunch Daily - Latest Startup News',
    preview: 'Top stories: AI startup raises $100M, new blockchain protocol...',
    timestamp: '2024-11-27T16:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '23',
    mailboxId: 'inbox',
    sender: 'calendar@google.com',
    subject: 'Event Reminder - Team Standup in 15 minutes',
    preview: 'Your event "Team Standup" starts at 10:00 AM...',
    timestamp: '2024-11-27T14:45:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '24',
    mailboxId: 'inbox',
    sender: 'it-support@company.com',
    subject: 'Password Reset Confirmation',
    preview: 'Your password has been successfully reset. If you did not...',
    timestamp: '2024-11-27T12:30:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '25',
    mailboxId: 'inbox',
    sender: 'client-success@saas.com',
    subject: 'Your Subscription Renewal',
    preview: 'Your annual subscription will renew on December 15, 2024...',
    timestamp: '2024-11-27T10:00:00Z',
    isRead: false,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '26',
    mailboxId: 'inbox',
    sender: 'github@noreply.com',
    subject: '[Repository] Issue #456 closed',
    preview: 'Issue #456 "Fix login bug" has been closed by @admin...',
    timestamp: '2024-11-26T17:30:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '27',
    mailboxId: 'inbox',
    sender: 'analytics@company.com',
    subject: 'Monthly Analytics Report - November',
    preview: 'Your website received 50,000 visitors this month, up 15%...',
    timestamp: '2024-11-26T15:00:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: true,
  },
  {
    id: '28',
    mailboxId: 'inbox',
    sender: 'legal@company.com',
    subject: 'NDA Document for Review',
    preview: 'Please review and sign the attached NDA document...',
    timestamp: '2024-11-26T13:15:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: true,
  },
  {
    id: '29',
    mailboxId: 'inbox',
    sender: 'vendor@supplier.com',
    subject: 'Invoice #98765 - Payment Due',
    preview: 'Your invoice for services rendered is now due...',
    timestamp: '2024-11-26T11:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '30',
    mailboxId: 'inbox',
    sender: 'community@stackoverflow.com',
    subject: 'Your question received 5 new answers',
    preview: 'Check out the new answers to your question about React hooks...',
    timestamp: '2024-11-26T09:30:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '31',
    mailboxId: 'inbox',
    sender: 'mentor@company.com',
    subject: '1-on-1 Meeting Scheduled',
    preview: 'Our monthly 1-on-1 meeting is scheduled for next Tuesday...',
    timestamp: '2024-11-25T16:00:00Z',
    isRead: false,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '32',
    mailboxId: 'inbox',
    sender: 'docker@hub.com',
    subject: 'New Docker Image Available',
    preview: 'A new version of your Docker image has been published...',
    timestamp: '2024-11-25T14:30:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '33',
    mailboxId: 'inbox',
    sender: 'compliance@company.com',
    subject: 'Annual Compliance Training Required',
    preview: 'Please complete your annual compliance training by Dec 31...',
    timestamp: '2024-11-25T12:00:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '34',
    mailboxId: 'inbox',
    sender: 'newsletter@medium.com',
    subject: 'Top Stories in Web Development',
    preview: 'This week\'s top stories: Next.js 14, React Server Components...',
    timestamp: '2024-11-25T10:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '35',
    mailboxId: 'inbox',
    sender: 'sales@company.com',
    subject: 'Q4 Sales Targets Review',
    preview: 'Let\'s discuss the Q4 sales performance and targets for next quarter...',
    timestamp: '2024-11-24T17:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '36',
    mailboxId: 'inbox',
    sender: 'devops@company.com',
    subject: 'Server Maintenance Window - Dec 5',
    preview: 'Scheduled maintenance will occur on Dec 5 from 2 AM to 4 AM...',
    timestamp: '2024-11-24T15:30:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '37',
    mailboxId: 'inbox',
    sender: 'research@company.com',
    subject: 'User Research Survey Results',
    preview: 'The results from our latest user research survey are in...',
    timestamp: '2024-11-24T13:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '38',
    mailboxId: 'inbox',
    sender: 'partner@agency.com',
    subject: 'Partnership Proposal',
    preview: 'We would like to discuss a potential partnership opportunity...',
    timestamp: '2024-11-24T11:15:00Z',
    isRead: false,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '39',
    mailboxId: 'inbox',
    sender: 'automation@zapier.com',
    subject: 'Your Zap "Email to Slack" triggered',
    preview: 'Your automation has successfully processed 150 items...',
    timestamp: '2024-11-23T18:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '40',
    mailboxId: 'inbox',
    sender: 'events@company.com',
    subject: 'Holiday Party Invitation',
    preview: 'You\'re invited to our annual holiday party on December 20...',
    timestamp: '2024-11-23T16:00:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '41',
    mailboxId: 'inbox',
    sender: 'bug-tracker@company.com',
    subject: 'Critical Bug Report - Production',
    preview: 'A critical bug has been reported in the payment processing module...',
    timestamp: '2024-11-23T14:00:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '42',
    mailboxId: 'inbox',
    sender: 'cloud@azure.com',
    subject: 'Azure Credits Expiring Soon',
    preview: 'Your Azure credits worth $500 will expire on December 31...',
    timestamp: '2024-11-23T12:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '43',
    mailboxId: 'inbox',
    sender: 'wordpress@updates.com',
    subject: 'WordPress 6.4 Update Available',
    preview: 'A new version of WordPress is available with security updates...',
    timestamp: '2024-11-22T17:30:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '44',
    mailboxId: 'inbox',
    sender: 'manager@company.com',
    subject: 'Performance Review Schedule',
    preview: 'Your annual performance review is scheduled for December 12...',
    timestamp: '2024-11-22T15:00:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '45',
    mailboxId: 'inbox',
    sender: 'newsletter@css-tricks.com',
    subject: 'CSS Grid Layout Tutorial',
    preview: 'Learn advanced CSS Grid techniques with our latest tutorial...',
    timestamp: '2024-11-22T13:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '46',
    mailboxId: 'inbox',
    sender: 'quality@company.com',
    subject: 'QA Test Results - Sprint 24',
    preview: 'The QA team has completed testing for Sprint 24. Results attached...',
    timestamp: '2024-11-22T11:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: true,
  },
  {
    id: '47',
    mailboxId: 'inbox',
    sender: 'kubernetes@updates.com',
    subject: 'Kubernetes Cluster Health Report',
    preview: 'Your Kubernetes cluster is running smoothly. 99.9% uptime...',
    timestamp: '2024-11-21T18:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '48',
    mailboxId: 'inbox',
    sender: 'customer@feedback.com',
    subject: 'Customer Feedback - 5 Star Review',
    preview: 'You received a 5-star review from a customer! "Excellent service..."',
    timestamp: '2024-11-21T16:00:00Z',
    isRead: false,
    isStarred: true,
    hasAttachment: false,
  },
  {
    id: '49',
    mailboxId: 'inbox',
    sender: 'database@company.com',
    subject: 'Database Backup Completed',
    preview: 'Daily database backup completed successfully at 2:00 AM...',
    timestamp: '2024-11-21T14:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '50',
    mailboxId: 'inbox',
    sender: 'typescript@updates.com',
    subject: 'TypeScript 5.3 Released',
    preview: 'TypeScript 5.3 is now available with new features and improvements...',
    timestamp: '2024-11-21T12:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  // Sent emails
  {
    id: '51',
    mailboxId: 'sent',
    sender: 'me@company.com',
    subject: 'Re: Project Proposal',
    preview: 'Thank you for the proposal. I have reviewed it and have some feedback...',
    timestamp: '2024-11-20T15:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
  {
    id: '52',
    mailboxId: 'sent',
    sender: 'me@company.com',
    subject: 'Meeting Request - Q4 Planning',
    preview: 'I would like to schedule a meeting to discuss Q4 planning...',
    timestamp: '2024-11-19T10:00:00Z',
    isRead: true,
    isStarred: false,
    hasAttachment: false,
  },
];
